services:
  frontend:
    build:
      context: ./Application
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
   

networks:
  app_network:
    driver: bridge